---
- name: usar un bucle en jinja2
  hosts: localhost
  connection: local
  vars: 
    - listahosts:
        - { nombre: "primero", ip: "1.1.1.1" }
        - { nombre: "segundo", ip: "1.1.1.2" }
        - { nombre: "tercero", ip: "1.1.1.3" }

  tasks:
    - name: generar el fichero desde plantilla
      template:  
         src: hosts.j2
         dest: /tmp/listahosts
  
